### ISSUE TITLE
Error in Automatic Deployment

### ISSUE THREAD

**Issue by In-vincible** [In-vincible/hourblog1#3]
@verma-varsha we are facing this deployment issue since #1 merge.
logs for the error:
```
-----> Python app detected
 !     The latest version of Python 3 is python-3.6.3 (you are using python-3.6.1, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-3.6.3).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing requirements with pip
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 22, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
           handler(path, prefixed_path, storage)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
           if not self.delete_file(path, prefixed_path, source_storage):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
           if self.storage.exists(prefixed_path):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 392, in exists
           return os.path.exists(self.path(name))
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 50, in path
           raise ImproperlyConfigured("You're using the staticfiles app "
       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by In-vincible** [comment]
I have not looked into the error but I hope you have set up your environment for python 3.6 and tested in the same.

**Comment by In-vincible** [comment]
I have resolved this issue and set up the postgres database too.

**Comment by In-vincible** [comment]
@verma-varsha be sure to delete db.squilite3 first and then run ```python manage.py migrate```,
and try  installing python3.6, docs given work just fine.
@verma-varsha 
After reading the above comments please mark this issue resolved.

**Comment by In-vincible** [comment]
I had to push few extra commits as deployment errors could only be tested with commits, so feel free to squash commits !!

**Comment by verma-varsha** [comment]
You can close the issue now. I've migrated my local repository to python3.6.
